SERVER_PORT: 9090
CONTEXT_PATH: /api

############# DATABASE INFO ##################
DATABASE_URL: localhost
DATABASE_PASSWORD: chaimaa123
DATABASE_USERNAME: chaimaa
DATABASE_NAME: USERS
DATABASE_PORT: 5432