server:
  port: ${SERVER_PORT:8085}
  servlet:
    contextPath: ${CONTEXT_PATH:/api}
spring:
  datasource:
    password: ${DATABASE_PASSWORD:chaimaa123}
    username: ${DATABASE_USERNAME:chaimaa}
    url: jdbc:postgresql://${DATABASE_URL:localhost}:${DATABASE_PORT:54320}/${DATABASE_NAME:USERS}
    driver-class-name: org.postgresql.Driver
  profiles:
    active: local

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc.batch_size: 30
        order_inserts: true
        jdbc.time_zone: UTC
        dialect: org.hibernate.dialect.PostgreSQLDialect
        types.print.banner: false
        format_sql: true